#include "LavaHeat.h"

//static boolean set by the lava particles when they are touched by the iceblock
bool LavaHeat::s_touchingIce = false;

//constructor
LavaHeat::LavaHeat(float heatAmount) : m_heatAmount{ heatAmount } {};

//returns the heat generated by this emitter to the given iceblock
float LavaHeat::getHeat(Iceblock* block)const {
	if (s_touchingIce) {
		s_touchingIce = false;
		return m_heatAmount;
	}
	return 0;
}

//returns a clone of the heat emitter
LavaHeat* LavaHeat::clone()const {
	return new LavaHeat(m_heatAmount);
}