#pragma once
#include "HeatEmitter.h"

//adds heat when the iceblock is within the trigger of the owning object
class LavaHeat : public HeatEmitter {
private:
	//the amount of heat to add
	float m_heatAmount;
public:
	//static boolean set by the lava particles when they are touched by the iceblock
	static bool s_touchingIce;

	//constructor
	LavaHeat(float heatAmount);

	//returns the heat generated by this emitter to the given iceblock
	virtual float getHeat(Iceblock* block)const override;

	//returns a clone of the heat emitter
	LavaHeat* clone()const override;
};