#pragma once
#include "HeatEmitter.h"

//distributes heat from a point in every direction
class PointHeat : public HeatEmitter {
private:
	//the radius of the pointheat
	float m_radius;

	//the core heat of the pointheat
	float m_coreHeat;

public:
	//constructor
	PointHeat(float radius, float coreHeat);

	//returns the heat generated by this emitter to the given iceblock
	virtual float getHeat(Iceblock* block)const override;

	//returns a clone of the heat emitter
	PointHeat* clone()const override;
};