#pragma once
#include "HeatEmitter.h"

//adds heat when the iceblock is within the trigger of the owning object
class TriggerHeat : public HeatEmitter {
private:
	//the amount of heat to add
	float m_heatAmount;
public:
	//constructor
	TriggerHeat(float heatAmount);

	//returns the heat generated by this emitter to the given iceblock
	virtual float getHeat(Iceblock* block)const override;

	//returns a clone of the heat emitter
	TriggerHeat* clone()const override;
};