#include "TriggerHeat.h"

//constructor
TriggerHeat::TriggerHeat(float heatAmount) : m_heatAmount{ heatAmount } {}

//returns the heat generated by this emitter to the given iceblock
float TriggerHeat::getHeat(Iceblock* block)const {
	//if the iceblock has the owning object as a trigger
	if (reb::Container* containerOwner = dynamic_cast<reb::Container*>(getOwner())) {
		if (hasOwner() && block->getBody()->hasTrigger(containerOwner)) {
			//return amount
			return m_heatAmount;
		}
	}
	//return zero otherwise
	return 0;
}

//returns a clone of the heat emitter
TriggerHeat* TriggerHeat::clone()const {
	return new TriggerHeat(m_heatAmount);
}